server:
  port: 8080

app:
  topic: users.v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: kafka
    password: kafkaConfluent
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    client-id: user-producer
    properties:
      schema.registry.url: http://localhost:8081
      use.latest.version: true
      auto.register.schemas: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all