server:
  port: 8089

app:
  topic: users.v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: kafka
    password: kafkaConfluent
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Use default physical naming strategy
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Optional: Format SQL queries for readability
        jdbc:
          time_zone: UTC  # Optional: Specify JDBC time zone

  kafka:
    bootstrap-servers: localhost:29092
    client-id: user-consumer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      group-id: user-svc
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
