server:
  port: 8089

app:
  topic: users.v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: kafka
    password: kafkaConfluent
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    client-id: user-consumer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      group-id: user-svc
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
